CREATE TABLE `contents` (
  `ID` int NOT NULL AUTO_INCREMENT,  
  `Name` varchar(50) NOT NULL,  
  `Data` varchar(2000) NOT NULL,  
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=308 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
